[build-system]
requires = ["maturin>=1.10,<2.0"]
build-backend = "maturin"

[project]
name = "statoxide"
version = "0.3.0"
requires-python = ">=3.8"
classifiers = [
    "Programming Language :: Rust",
    "Programming Language :: Python :: Implementation :: CPython",
    "Programming Language :: Python :: Implementation :: PyPy",
]
description = "High-performance statistical computing library written in Rust"
readme = "README.md"
license = "MIT AND Apache-2.0"
keywords = ["statistics", "regression", "machine-learning", "data-science"]
authors = [
    {name = "EthanNov56", email = "yichen_1226@163.com"},
]
