[package]
name = "so-tsa"
version.workspace = true
edition.workspace = true
authors.workspace = true
description.workspace = true
license.workspace = true
readme.workspace = true

[dependencies]
ndarray.workspace = true
rand.workspace = true
serde = { version = "1.0", features = ["derive"] }
chrono = { version = "0.4", features = ["serde"] }
statrs = "0.17"

so-core = { workspace = true }
so-linalg = { workspace = true }
so-stats = { workspace = true }

[dev-dependencies]
approx = "0.5"
