[package]
name = "so-tsa"
version.workspace = true
edition.workspace = true
authors.workspace = true
description.workspace = true
license.workspace = true
readme.workspace = true

[dependencies]
ndarray.workspace = true
rand.workspace = true
so-core = { path = "../so-core" }
so-linalg = { path = "../so-linalg" }
so-stats = { path = "../so-stats" }
chrono = { version = "0.4", features = ["serde"] }
statrs = "0.17"

[dev-dependencies]
approx = "0.5"